"""initial_db_state

Revision ID: 72d318fa5242
Revises: 
Create Date: 2025-04-05 18:49:30.960745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d318fa5242'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('created_at')
    )
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_updated_at'), 'comments', ['updated_at'], unique=False)
    op.create_table('pixel_events',
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('pixel_id', sa.Integer(), nullable=False),
    sa.Column('stake_amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('log_index', 'timestamp', 'pixel_id')
    )
    op.create_index(op.f('ix_pixel_events_deleted_at'), 'pixel_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pixel_events_log_index'), 'pixel_events', ['log_index'], unique=False)
    op.create_index(op.f('ix_pixel_events_owner'), 'pixel_events', ['owner'], unique=False)
    op.create_index(op.f('ix_pixel_events_pixel_id'), 'pixel_events', ['pixel_id'], unique=False)
    op.create_index(op.f('ix_pixel_events_timestamp'), 'pixel_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pixel_events_updated_at'), 'pixel_events', ['updated_at'], unique=False)
    op.create_table('pixels',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('stake_amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('hash', sa.String(), server_default='0x0000000000000000000000000000000000000000000000000000000000000000', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pixels_color'), 'pixels', ['color'], unique=False)
    op.create_index(op.f('ix_pixels_deleted_at'), 'pixels', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pixels_id'), 'pixels', ['id'], unique=False)
    op.create_index(op.f('ix_pixels_owner'), 'pixels', ['owner'], unique=False)
    op.create_index(op.f('ix_pixels_updated_at'), 'pixels', ['updated_at'], unique=False)
    op.create_table('project_events',
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=100), nullable=False),
    sa.Column('project_address', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('gas', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('log_index', 'timestamp')
    )
    op.create_index(op.f('ix_project_events_deleted_at'), 'project_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_events_log_index'), 'project_events', ['log_index'], unique=False)
    op.create_index(op.f('ix_project_events_project_address'), 'project_events', ['project_address'], unique=False)
    op.create_index(op.f('ix_project_events_timestamp'), 'project_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_project_events_updated_at'), 'project_events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_project_events_user'), 'project_events', ['user'], unique=False)
    op.create_table('project_snapshots',
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('nbr_active_pixels', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nbr_controlled_pixels', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('best_cost', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('best_row', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('best_col', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('gas_available', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('gas_used', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('created_at')
    )
    op.create_index(op.f('ix_project_snapshots_address'), 'project_snapshots', ['address'], unique=False)
    op.create_index(op.f('ix_project_snapshots_deleted_at'), 'project_snapshots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_snapshots_title'), 'project_snapshots', ['title'], unique=False)
    op.create_index(op.f('ix_project_snapshots_updated_at'), 'project_snapshots', ['updated_at'], unique=False)
    op.create_table('projects',
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('image_grid', sa.LargeBinary(), nullable=False),
    sa.Column('image_mask', sa.LargeBinary(), nullable=False),
    sa.Column('image_h', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('image_w', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nbr_active_pixels', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('best_cost', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('best_row', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('best_col', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('gas_available', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('gas_used', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_projects_address'), 'projects', ['address'], unique=False)
    op.create_index(op.f('ix_projects_creator'), 'projects', ['creator'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('wallet', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oldest_accepted_token_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('joined_pixamut_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tech_id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_joined_pixamut_at'), 'users', ['joined_pixamut_at'], unique=False)
    op.create_index(op.f('ix_users_tech_id'), 'users', ['tech_id'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_wallet'), 'users', ['wallet'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_tech_id'), table_name='users')
    op.drop_index(op.f('ix_users_joined_pixamut_at'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_creator'), table_name='projects')
    op.drop_index(op.f('ix_projects_address'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_snapshots_updated_at'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_title'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_deleted_at'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_address'), table_name='project_snapshots')
    op.drop_table('project_snapshots')
    op.drop_index(op.f('ix_project_events_user'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_updated_at'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_timestamp'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_project_address'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_log_index'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_deleted_at'), table_name='project_events')
    op.drop_table('project_events')
    op.drop_index(op.f('ix_pixels_updated_at'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_owner'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_id'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_deleted_at'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_color'), table_name='pixels')
    op.drop_table('pixels')
    op.drop_index(op.f('ix_pixel_events_updated_at'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_timestamp'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_pixel_id'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_owner'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_log_index'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_deleted_at'), table_name='pixel_events')
    op.drop_table('pixel_events')
    op.drop_index(op.f('ix_comments_updated_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
